name: Deploy to Arweave

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # or your preferred version
    
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Deploy to Arweave
      run: |
        npm install -g arkb@latest
        echo "${{ secrets.ARWEAVE_WALLET }}" > wallet.json
        arbk wallet-save wallet.json
        arkb --auto-confirm deploy build 
